# Site settings
author: Anthony
title: Cobra Kai 
header-img: img/home-bg.png
email: antonio-molina@att.net
copyright_name: Anthony
description: > # this means to ignore newlines until "baseurl:"
  Rogue Coder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Antichrist369

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
